### ISSUE TITLE
GLTFRealityKitLoader bad material rendering on some GLB Files

### ISSUE THREAD

**Issue by polycamnick** [warrenm/GLTFKit2#51]
Loading certain GLB files via GLTFRealityKitLoader into a RealityView scene on visionOS is resulting in bad rendering

Example 1:
Expected:
<img width="789" alt="Screenshot 2024-01-16 at 10 12 01 PM" src="https://github.com/warrenm/GLTFKit2/assets/150742504/e1b98c20-f32f-468e-9367-90b0855f4101">

Result:
<img width="985" alt="Screenshot 2024-01-16 at 10 14 40 PM" src="https://github.com/warrenm/GLTFKit2/assets/150742504/f2f1fee9-7774-480f-929b-41181557b945">

Example 2: 
Expected: 
<img width="731" alt="Screenshot 2024-01-16 at 10 24 39 PM" src="https://github.com/warrenm/GLTFKit2/assets/150742504/18ab3967-8d2d-427b-b537-442c3b124cec">

Result:
<img width="940" alt="Screenshot 2024-01-16 at 9 50 05 PM" src="https://github.com/warrenm/GLTFKit2/assets/150742504/fd6a3b46-9b1c-458a-ba73-43f9d85cf84d">

GLB Samples:
[tank.glb.zip](https://github.com/warrenm/GLTFKit2/files/13958919/tank.glb.zip)

More samples providable upon request, GitHub attachments max at 25mb

**Comment by warrenm** [comment]
Thanks for the report. This should be enough to start looking into the issue.

**Comment by warrenm** [comment]
This was due to a misunderstanding of how RealityKit maps the materials list in a `ModelComponent` to the corresponding `MeshResource` primitives. It should be fixed as of 95d6aaf.

If you're able to test this fix without me needing to spin a new release, I'd appreciate any feedback. Otherwise this fix will be incorporated into an upcoming release. Thanks again for the report.

**Comment by cpheinrich** [comment]
> This was due to a misunderstanding of how RealityKit maps the materials list in a `ModelComponent` to the corresponding `MeshResource` primitives. It should be fixed as of [95d6aaf](https://github.com/warrenm/GLTFKit2/commit/95d6aafbad9c9bcf0b070913df7bc30d66ac045b).
> 
> If you're able to test this fix without me needing to spin a new release, I'd appreciate any feedback. Otherwise this fix will be incorporated into an upcoming release. Thanks again for the report.

Thanks for taking a look Warren! We'll test it out and revert back.

**Comment by polycamnick** [comment]
Thanks for the rapid turnaround

Still seeing issues with 95d6aaf

<img width="842" alt="Screenshot 2024-01-17 at 1 48 36 PM" src="https://github.com/warrenm/GLTFKit2/assets/150742504/82bf70e1-61c1-4c42-ae0c-df77ae46954e">
<img width="895" alt="Screenshot 2024-01-17 at 1 49 22 PM" src="https://github.com/warrenm/GLTFKit2/assets/150742504/f7dd899b-7f4c-4d35-83dd-c28b731e6b25">

**Comment by warrenm** [comment]
Can you share a .glb that reproduces this issue? I suspect it's a separate bug.

**Comment by polycamnick** [comment]
I can but GLB doesn't compress well and these files are bigger than the GitHub max attachment size

Google Drive link work?
https://drive.google.com/file/d/1MelF1Qo_kE83h4Ym_cYbWxqMWOzNSZYI/view?usp=share_link

**Comment by warrenm** [comment]
The immediate issue here is that we're trying to extract a color channel from a monochrome image as if it's an RGBA image. That's fairly easy to fix, but in the process of fixing it, I've encountered a lot of flakiness in the runtime behavior, and the perennial flakiness of Swift+lldb is making it hard to debug. I'll continue looking at this.

**Comment by warrenm** [comment]
The situation should be much improved with c5501dd. In addition to never attempting to extract a channel from a single-channel image, I switched to a more efficient method from the Accelerate framework to do the extraction when necessary. I also added some defensive image decoding code that only runs on visionOS to address some problems I encountered there.

You're likely to hit validation errors when running with the Metal API validation layer due to the use of 8K images for all material properties, but you can address that when and how you see fit.

**Comment by polycamnick** [comment]
Tested with https://github.com/warrenm/GLTFKit2/commit/c5501dd7fe78bdb4cbecddb849d0eee251ef687d

Things do seem improved, there's intermittency on some of the failures (not sure if that's this library or RealityKit/visionOS Simulator)

However some of the models (the jet engine) remain broken with that "zebra" white/gray material failure mode.

Here's is another model that consistently zebras: https://drive.google.com/file/d/1cQDxuaT44CjQHENjNUlJSmaspaRd8Srp/view?usp=share_link

Are you able to reproduce that issue with that model?
- Xcode 15.2
- visionOS Simulator

(edit:) my testing environment:
1. Out-of-the-box new visionOS App via Xcode
2. GLTFKit2.0 installed via SMP pointed to `master`
3. GLB loading done via the local filesystem
4. Resulting ModelEntity placed via RealityView in the default ImmersiveSpace.

Nothing too crazy here, I can provide the project if that helps with reproduction

<img width="800" alt="Screenshot 2024-01-19 at 9 54 36 AM" src="https://github.com/warrenm/GLTFKit2/assets/150742504/168113ef-4a30-4ca0-8f98-74b0e1a6c8e5">
<img width="349" alt="Screenshot 2024-01-19 at 9 54 48 AM" src="https://github.com/warrenm/GLTFKit2/assets/150742504/63158aa2-5ec1-47c3-892d-4d2e1378676d">

**Comment by warrenm** [comment]
Be happy to take a look at a sample project if you can provide it. The table model seems to consistently render without obvious bugs for me with Xcode 15.2 + visionOS Simulator 1.0:

<img width="512" alt="table" src="https://github.com/warrenm/GLTFKit2/assets/39937547/df311d3c-ce5d-447c-897e-c5f8a9e0b608">

I do see one failure on the console:
`callDecodeImage:2006: *** ERROR: decodeImageImp failed - NULL _blockArray`
and the app crashes with the Metal validation layer enabled (due to the large image size), but without validation enabled, it renders as above.

**Comment by polycamnick** [comment]
Sample project, very simple modifications to the default project setup from 15.2

Large size due to embedded gib files

Hope I'm just holding it wrong :) 

https://drive.google.com/file/d/1gPBJwy8YBSyL7oc6mHnpwCjqufudWp9L/view?usp=share_link

**Comment by warrenm** [comment]
I think if you're consuming the framework as a Swift package (which I don't recommend to anyone, but grudgingly support), it uses the contents of the Package.swift in the checkout to determine how to build. In this case, because the package file points to the latest GitHub release, you're not actually building and linking against the code at top of tree; you're linking against version 0.5.7, which doesn't include the changes made to address this issue.

**Comment by warrenm** [comment]
Here's an XCFramework built from top of tree. It should work as a drop-in replacement for the SPM dependency.

https://drive.google.com/file/d/1SmnapYontNls7Wuwv2lyXmhs648derKV/view?usp=sharing

SHA256: `9caf87301f184abb6a268053f5e89f07d06002acba7a5532ec89bcb6b804b1cb`

**Comment by polycamnick** [comment]
Oh wow okay that "makes sense" but damn 

So my project's package.swift points to GLTFKit master, and so the git history of the local GLTFKit copy shows your recent commits (which is why I thought I was using them)

But because GLTFKit's package.swift on master points to a specific release, it "overrides" my project's package.swift file, and what actually gets installed is the older release copy...

HUH. Good to know. 

Okay that's great... I'll be able to test this later today. 

Thanks Warren! Much appreciated

**Comment by warrenm** [comment]
Yep, you got it. Sorry for the confusion. I only distribute binaries because SPM still doesn't support mixed-language targets after all these years. Maybe we get that [some time this decade](https://github.com/apple/swift-evolution/blob/main/proposals/0403-swiftpm-mixed-language-targets.md).

**Comment by spelman7** [comment]
Thanks so much for the support here, @warrenm! 

If you're interested, we'd be happy to give you free access to Polycam Pro. If you create a Polycam account, send me the email address you used to create it, and I'll upgrade it. My email is my first name "elliott" at polycam.ai

**Comment by polycamnick** [comment]
Perfection, thank you so much @warrenm 
![Screenshot 2024-01-19 at 2 42 14 PM](https://github.com/warrenm/GLTFKit2/assets/150742504/f26a54df-5b97-4cf5-a3a7-9917ed109b75)

**Comment by warrenm** [comment]
Sweet! Thanks for sticking with it.

**Comment by spelman7** [comment]
@warrenm Awesome! Just upgraded your Polycam account - you should have access to Pro indefinitely.
